### ISSUE TITLE
Filtering gets stuck in endless loop

### ISSUE THREAD

**Issue by MaxKman** [sdparekh/zUMIs#52] opened 2018-08-12 19:32 UTC
Hi,

excited to try the new zUMIs version. Unfortunately I can't get the test dataset to work. Here is the yaml file I used:
[zumis-test-example.yaml.txt](https://github.com/sdparekh/zUMIs/files/2281261/zumis-test-example.yaml.txt)

console output:
```
 You provided these parameters:
 YAML file:     zumis-test-example.yaml
 zUMIs directory:               /home/makaufm/zUMIs
 STAR executable                STAR
 samtools executable            samtools
 pigz executable                pigz
 Rscript executable             Rscript
 RAM limit:   null
 zUMIs version 2.0


Filtering...
```
No progress after that. I noticed that in the .tmpMerge folder within the zUMIs output folder an endless stream of 1kb files is created:
![image](https://user-images.githubusercontent.com/30081989/44005653-fcbfddfc-9e76-11e8-98fb-bb06020e1c1d.png)

**Comment by cziegenhain** [comment] 2018-08-13 07:02
Hey Max,

sorry that your upgrade to zUMIs2 is not going so smooth!
I tried to recreate this issue myself.
The problem is you are simply missing a space in you project name.
line 8 `project: MB_Test`

Also in the end your line 81 (containing samtools executable) is malformatted. you can simply delete the lines 81-85 and zUMIs will add them correctly during the next call :)

**Comment by MaxKman** [comment] 2018-08-13 16:35
Hey Christoph,

thanks for the quick answer, that has resolved the issue. However, now I have a new problem, which I am guessing is a STAR bug: https://github.com/alexdobin/STAR/issues/470

Unless you have a better explanation ;)

Best
Max

**Comment by cziegenhain** [comment] 2018-08-13 16:54
Very peculiar! I haven't generated any genome index with the newest STAR version, I have continued to use my previously made indices.
Here is my genomeParameters.txt file for reference:

> /opt/bin/STAR   --runMode genomeGenerate   --runThreadN 5   --genomeDir /data/share/ngs/genomes/Human/hg38/STAR5idx_noGTF   --genomeFastaFiles /data/share/ngs/genomes/Human/hg38/hg38.fa      --limitGenomeGenerateRAM 111000000000
> versionGenome   20201
> genomeFastaFiles        /data/share/ngs/genomes/Human/hg38/hg38.fa
> genomeSAindexNbases     14
> genomeChrBinNbits       18
> genomeSAsparseD 1
> sjdbOverhang    0
> sjdbFileChrStartEnd     -
> sjdbGTFfile     -
> sjdbGTFchrPrefix        -
> sjdbGTFfeatureExon      exon
> sjdbGTFtagExonParentTranscript  transcript_id
> sjdbGTFtagExonParentGene        gene_id
> sjdbInsertSave  Basic

**Comment by MaxKman** [comment] 2018-08-13 19:33
It is definitely a STAR problem. I now generated a new index with STAR 2.5.4a and it finally starts mapping...

**Comment by cziegenhain** [comment] 2018-08-13 19:45
Sounds good!
Hope that everything runs fine for you now. 

I'll close this issue, but feel free to contact us whenever you need further help.

**Closed by cziegenhain** 2018-08-13 19:45 UTC
