### ISSUE TITLE
Issues with non standard scRNA protocols

### ISSUE THREAD

**Issue by iimaz** [sdparekh/zUMIs#12] opened 2017-11-23 13:47 UTC
Dear zUMIs developers,

 I am trying to apply zUMIs to a non standard scRNAseq protocol (https://www.nature.com/articles/s41467-017-00244-w.pdf). I think zUMIs should not have a problem with such data set. However, I am stuck with an error that I simply have no idea where it is coming from. Please find my command line and the error message which is then followed by more errors (possibly as a consequence of the first one). Do you have any idea of what could be happening? Thank you!

zUMIs-master.sh -f ./SRR5120019_1.fastq -r ./SRR5120019_2.fastq -c 1-11 -m 12-22 -l 125 -g /mnt/a/scRNAseq/resources/mouse -a /mnt/a/scRNAseq/resources/mouse/Mus_musculus.GRCm38.81.gtf -n test -p 20

Make sure you have more than 29G RAM and 20 processors available. 

Your jobs will be started from filtering. 

 You provided these parameters:
 SLURM workload manager:	no
 Summary Stats to produce:	yes
 Start the pipeline from:	filtering
 A custom mapped BAM:		NA
 Custom filtered FASTQ:		no
 Barcode read:			./SRR5120019_1.fastq
 cDNA read:			./SRR5120019_2.fastq
 Study/sample name:		test
 Output directory:		/mnt/a/scRNAseq/nanogrid/ftp.sra.ebi.ac.uk/vol1/fastq/SRR512/009/SRR5120019
 Cell/sample barcode range:	1-11
 UMI barcode range:		12-22
 Retain cell with >=N reads:	100
 Genome directory:		/mnt/a/scRNAseq/resources/mouse
 GTF annotation file:		/mnt/a/scRNAseq/resources/mouse/Mus_musculus.GRCm38.81.gtf
 Number of processors:		20
 Read length:			125
 Strandedness:			0
 Cell barcode Phred:		20
 UMI barcode Phred:		20
 bases below phred in CellBC:	1
 bases below phred in UMI:	1
 Barcodes:			NA
 zUMIs directory:		/home/iimaz/Tools/zUMIs
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 Additional STAR parameters:	
 STRT-seq data:			no
 InDrops data:			no
 Library read for InDrops:	NA
 Barcode read2(STRT-seq):	NA
 Barcode read2 range(STRT-seq):	0-0
 Bases(G) to trim(STRT-seq):	3
 Subsampling reads:		0 

Raw reads: 96133 
Filtered reads: 84680 

Nov 23 07:38:58 ..... started STAR run
Nov 23 07:38:58 ..... loading genome
Nov 23 07:39:08 ..... processing annotations GTF
Nov 23 07:39:16 ..... inserting junctions into the genome indices
Nov 23 07:40:29 ..... started 1st pass mapping
Nov 23 07:41:01 ..... finished 1st pass mapping
Nov 23 07:41:01 ..... inserting junctions into the genome indices
Nov 23 07:42:14 ..... started mapping
Nov 23 07:42:41 ..... finished successfully
sort: invalid option -- 'O'
sort: invalid option -- 'T'
open: No such file or directory
[bam_sort_core] fail to open file bam
sort: invalid option -- 'O'
sort: invalid option -- 'T'
open: No such file or directory
[bam_sort_core] fail to open file sam
Loading required package: optparse
[1] "I am loading useful packages..."
[1] "2017-11-23 07:42:41 CST"
[1] "I am loading Rsubread 1.26.0..."
Warning message:
In if (installed.packages()[grep("Rsubread", installed.packages()),  :
  the condition has length > 1 and only the first element will be used
[1] "I am making annotations in SAF... This will take less than 3 minutes..."
[1] "2017-11-23 07:42:48 CST"
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Warning message:
In .get_cds_IDX(type, phase) :
  The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.
'select()' returned 1:many mapping between keys and columns
[1] "I am making count tables...This will take a while!!"
[1] "2017-11-23 07:43:48 CST"

ERROR: invalid parameter: '/mnt/a/scRNAseq/nanogrid/ftp.sra.ebi.ac.uk/vol1/fastq/SRR512/009/SRR5120019/test.aligned.sorted.bam.in'

Error in file(file, "rt") : cannot open the connection
Calls: makeGEprofile -> featureCounts -> read.delim -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file './.Rsubread_featureCounts_pid8801': No such file or directory
Execution halted
[1] "I am loading useful packages for plotting..."
[1] "2017-11-23 07:43:49 CST"
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/mnt/a/scRNAseq/nanogrid/ftp.sra.ebi.ac.uk/vol1/fastq/SRR512/009/SRR5120019/zUMIs_output/expression/test.dgecounts.rds', probable reason 'No such file or directory'
Execution halted

**Comment by sdparekh** [comment] 2017-11-23 13:58
Hi Iimaz,

Thanks for using zUMIs! It seems that either you do not have "samtools" installed or samtools is not in PATH or it is called differently. 

You can use a custom path to samtools using the -t parameter in zUMIs.
Check **"Program paths"** section of the usage Wiki for more information:
https://github.com/sdparekh/zUMIs/wiki/Usage

I'm closing the issue for now, but feel free to reopen when you encounter further problems.

Best,
Swati

**Closed by sdparekh** 2017-11-23 13:58 UTC

**Comment by iimaz** [comment] 2017-11-23 14:23
Dear Swati,

 Thank you for your quick answer. I think the path to samtools is not the problem, because I do have samtools in PATH (STAR and pigz as well ). To double check that, I have also provided samtools executable using -t parameter and got the same error message. I am using samtools 1.19. Could that be the problem?

Best,
Ivan

**Comment by iimaz** [comment] 2017-11-23 14:39
Small update. I updated samtools version to the latest and now got a different error. Thank you for your help.

zUMIs-master.sh -f ./SRR5120019_1.fastq -r ./SRR5120019_2.fastq -c 1-11 -m 12-22 -l 125 -g /mnt/a/scRNAseq/resources/mouse -a /mnt/a/scRNAseq/resources/mouse/Mus_musculus.GRCm38.81.gtf -n test -p 20 -t
Your jobs will run on this machine. 


Make sure you have more than 29G RAM and 20 processors available. 


Your jobs will be started from filtering. 




 You provided these parameters:
 SLURM workload manager:	no
 Summary Stats to produce:	yes
 Start the pipeline from:	filtering
 A custom mapped BAM:		NA
 Custom filtered FASTQ:		no
 Barcode read:			./SRR5120019_1.fastq
 cDNA read:			./SRR5120019_2.fastq
 Study/sample name:		test
 Output directory:		/mnt/a/scRNAseq/nanogrid/ftp.sra.ebi.ac.uk/vol1/fastq/SRR512/009/SRR5120019
 Cell/sample barcode range:	1-11
 UMI barcode range:		12-22
 Retain cell with >=N reads:	100
 Genome directory:		/mnt/a/scRNAseq/resources/mouse
 GTF annotation file:		/mnt/a/scRNAseq/resources/mouse/Mus_musculus.GRCm38.81.gtf
 Number of processors:		20
 Read length:			125
 Strandedness:			0
 Cell barcode Phred:		20
 UMI barcode Phred:		20
 # bases below phred in CellBC:	1
 # bases below phred in UMI:	1
 Barcodes:			NA
 zUMIs directory:		/home/iimaz/Tools/zUMIs
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 Additional STAR parameters:	
 STRT-seq data:			no
 InDrops data:			no
 Library read for InDrops:	NA
 Barcode read2(STRT-seq):	NA
 Barcode read2 range(STRT-seq):	0-0
 Bases(G) to trim(STRT-seq):	3
 Subsampling reads:		0 


Raw reads: 96133 
Filtered reads: 84680 

Nov 23 08:31:43 ..... started STAR run
Nov 23 08:31:43 ..... loading genome
Nov 23 08:31:52 ..... processing annotations GTF
Nov 23 08:32:00 ..... inserting junctions into the genome indices
Nov 23 08:33:14 ..... started 1st pass mapping
Nov 23 08:33:46 ..... finished 1st pass mapping
Nov 23 08:33:46 ..... inserting junctions into the genome indices
Nov 23 08:35:00 ..... started mapping
Nov 23 08:35:27 ..... finished successfully
[bam_sort_core] merging from 0 files and 20 in-memory blocks...
[bam_sort_core] merging from 0 files and 20 in-memory blocks...
Loading required package: optparse
[1] "I am loading useful packages..."
[1] "2017-11-23 08:35:27 CST"
[1] "I am loading Rsubread 1.26.0..."
Warning message:
In if (installed.packages()[grep("Rsubread", installed.packages()),  :
  the condition has length > 1 and only the first element will be used
[1] "I am making annotations in SAF... This will take less than 3 minutes..."
[1] "2017-11-23 08:35:34 CST"
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Warning message:
In .get_cds_IDX(type, phase) :
  The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.
'select()' returned 1:many mapping between keys and columns
[1] "I am making count tables...This will take a while!!"
[1] "2017-11-23 08:36:34 CST"

        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.26.0

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S /mnt/a/scRNAseq/nanogrid/ftp.sra.ebi.ac.uk ... ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : no                                               ||
||         Strand specific : no                                               ||
||      Multimapping reads : primary only                                     ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file ./.Rsubread_UserProvidedAnnotation_pid11597 ...       ||
||    Features : 222869                                                       ||
||    Meta-features : 24807                                                   ||
||    Chromosomes/contigs : 66                                                ||
||                                                                            ||
|| Process BAM file /mnt/a/scRNAseq/nanogrid/ftp.sra.ebi.ac.uk/vol1/fastq ... ||
||    Single-end reads are included.                                          ||
||    Assign reads to features...                                             ||
||    Total reads : 84680                                                     ||
||    Successfully assigned reads : 4 (0.0%)                                  ||
||    Running time : 0.00 minutes                                             ||
||                                                                            ||
||                         Read assignment finished.                          ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//


        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.26.0

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S /mnt/a/scRNAseq/nanogrid/ftp.sra.ebi.ac.uk ... ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : no                                               ||
||         Strand specific : no                                               ||
||      Multimapping reads : primary only                                     ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file ./.Rsubread_UserProvidedAnnotation_pid11597 ...       ||
||    Features : 690647                                                       ||
||    Meta-features : 40893                                                   ||
||    Chromosomes/contigs : 73                                                ||
||                                                                            ||
|| Process BAM file /mnt/a/scRNAseq/nanogrid/ftp.sra.ebi.ac.uk/vol1/fastq ... ||
||    Single-end reads are included.                                          ||
||    Assign reads to features...                                             ||
||    Total reads : 84680                                                     ||
||    Successfully assigned reads : 1 (0.0%)                                  ||
||    Running time : 0.00 minutes                                             ||
||                                                                            ||
||                         Read assignment finished.                          ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

Error in if (sigmasq > signif(.Machine$double.xmax, 6)) { : 
  missing value where TRUE/FALSE needed
Calls: makeGEprofile ... eval -> mclustBIC -> mstep -> eval -> eval -> mstepE
Execution halted
[1] "I am loading useful packages for plotting..."
[1] "2017-11-23 08:36:44 CST"
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/mnt/a/scRNAseq/nanogrid/ftp.sra.ebi.ac.uk/vol1/fastq/SRR512/009/SRR5120019/zUMIs_output/expression/test.dgecounts.rds', probable reason 'No such file or directory'
Execution halted

**Comment by sdparekh** [comment] 2017-11-23 14:54
Hi Ivan,
Good to know that the samtools problem is solved.
For the second issue: Can you give me ls -lhd in your output directory please?

**Comment by iimaz** [comment] 2017-11-23 14:57
Sure:

cd zUMIs_output/
[iimaz@ema zUMIs_output]$ ls -lhd
drwxrwxr-x. 5 iimaz iimaz 4.0K Nov 23 08:31

Thanks again =)

**Comment by sdparekh** [comment] 2017-11-23 15:19
Sorry, I meant the "/mnt/a/scRNAseq/nanogrid/ftp.sra.ebi.ac.uk/vol1/fastq/SRR512/009/SRR5120019"

I see that only a couple of reads have been assigned to features and I find it alarming. I wanted to know if your BAM file was generated correctly and if any other intermediate files were missing. How many reads mapped to genome? You can check that in "/mnt/a/scRNAseq/nanogrid/ftp.sra.ebi.ac.uk/vol1/fastq/SRR512/009/SRR5120019/test.Log.final.out" ?

Since this is from an SRR file, I will check later by running it in on my own to see if I can reproduce the error.

**Comment by iimaz** [comment] 2017-11-24 11:55
Hi Swati,

 Following your observations. I blasted the reads and realise I am mapping a weird bacteria and therefore nothing was mapping. I got the wrong ftp apparently =S. It is now running fine. Thank you for your quick support. Your tool is really useful. 

Best,
Ivan

**Comment by sdparekh** [comment] 2017-11-24 12:27
Hi Ivan,

I am happy that your issue is resolved. Thanks again for using zUMIs and let us know if you encounter any other problems :)

Best,
Swati
