### ISSUE TITLE
Counting Step: Error: negative length vectors are not allowed

### ISSUE THREAD

**Issue by JuliaNiggemeyer** [sdparekh/zUMIs#94] opened 2018-12-04 13:36 UTC
Hi =)

I get an error in the counting step. I'm using zUMIs for data with two barcode fastq-files (i7 index & cell BC). For the barcode list I merged the cell BCs with the respective i7 indices like this:

> AAAACTTAAGGCGA
> AAAGTTTAAGGCGA
> AAATTGTAAGGCGA
> AAGATTTAAGGCGA
> AATACATAAGGCGA

Here's the relevant part of the outfile: 

> Counting...
> [ ... Rsubread stuff ... ]
> [bam_sort_core] merging from 28 files and 4 in-memory blocks...
> [bam_sort_core] merging from 28 files and 4 in-memory blocks...
> [1] "Here are the detected subsampling options:"
> [1] "Automatic downsampling"
> [1] "Working on barcode chunk 1 out of 2"
> [1] "Processing 2405 barcodes in this chunk..."
> **Error: negative length vectors are not allowed**
> Execution halted
> Descriptive statistics...
> [1] "I am loading useful packages for plotting..."
> [1] "2018-11-30 21:50:45 CET"
> Error in gzfile(file, "rb") : cannot open the connection
> Calls: readRDS -> gzfile
> In addition: Warning message:
> In gzfile(file, "rb") :
>   cannot open compressed file '/data/sfb1243cs/htp/A06/WT1_Project/seq2/2_zUMIs//zUMIs_output/expression/WT1_seq2.dgecounts.rds', probable reason 'No such file or directory'
> Execution halted

Here are my BCs, yaml and the complete outfile (had to add .txt for GitHub compatibility):
[BC.Indices.txt](https://github.com/sdparekh/zUMIs/files/2644120/BC.Indices.txt)
[WT1_seq2.yaml.txt](https://github.com/sdparekh/zUMIs/files/2644096/WT1_seq2.yaml.txt)
[zUMIs.out.txt](https://github.com/sdparekh/zUMIs/files/2644097/zUMIs.out.txt)

I'm happy with any help!
Thanks =)

**Comment by cziegenhain** [comment] 2018-12-07 20:53
Hey,

I traced the error message quite precisely by now to the downsampling in exon/intron count tables.
To investigate further, can you 1) half the RAM limit and 2) switch off intron counting and report what happens?

Best,
C

**Comment by JuliaNiggemeyer** [comment] 2018-12-11 10:47
Hi,

thanks for your help! Attached you find the new yaml and outfile.

[WT1_seq2.yaml.txt](https://github.com/sdparekh/zUMIs/files/2667167/WT1_seq2.yaml.txt)
[zUMIs.out.txt](https://github.com/sdparekh/zUMIs/files/2667169/zUMIs.out.txt)

Best, Julia

**Comment by sdparekh** [comment] 2018-12-13 10:30
Hi,

The new yaml file you specified mem_limit: 50000. The mem_limit is in GB so if you want to say 50GB then please specify mem_limit: 50. 

Another thing I noticed is that none of the annotated barcodes were detected. Please check the following:
1) if the file path to BC_indices is correct
2) if the list of BC is correct (i.e. that matches the concatenated R1 and R2 sequences.
3) check if you have wrong order of merging R1 and R2 in the BC_indices list.

Best, 
Swati

**Comment by JuliaNiggemeyer** [comment] 2018-12-17 10:00
Hi,
I now ran some tests with the correct settings:
- mem-limit: 50
- correct BC file (indeed it was a wrong one fo the last try)
- the BC/Index order seems to have been correct before (BC first, then Index), it didn't work the other way round

With these settings I got apparently intact zUMIs output with and without intron counting. Was the mem-limit the problem then? There was just one warning in the end of the outfile, is this an issue?

> Warning message:
> In bind_rows_(x, .id) :
>   binding character and factor vector, coercing into character vector
>             used   (Mb) gc trigger    (Mb)   max used    (Mb)
> Ncells   1836065   98.1    5311716   283.7    6639645   354.6
> Vcells 361713164 2759.7 6399132143 48821.6 7956528139 60703.5

Thanks!
Julia

**Comment by sdparekh** [comment] 2018-12-17 10:42
Hi Julia,

The warning is not an issue. I am glad that the issue is resolved. We will investigate in detail what went wrong in the first issue but for now it looks like it was the mem_limit. 

BC/Index order should be the same order as your file order. 

I will close this issue for now but feel free to write again.

Best,
Swati

**Comment by JuliaNiggemeyer** [comment] 2018-12-17 10:43
Perfect, thanks!

**Closed by sdparekh** 2018-12-17 10:42 UTC
