### ISSUE TITLE
Problems encountered in Smartseq3 data processing

### ISSUE THREAD

**Issue by zmf0621** [sdparekh/zUMIs#297] opened 2021-12-06 08:18 UTC
Hi Team, congrats on the awesome software! I used zUMIs today for a Smartseq3 data and there was such a problem at first:

[1] "2021-12-06 15:17:51 CST"
[1] "Coordinate sorting intermediate bam file..."
[bam_sort_core] merging from 0 files and 50 in-memory blocks...
[1] "2021-12-06 15:18:22 CST"
[1] "Hamming distance collapse in barcode chunk 1 out of 1"
Error in mclapply(1:nrow(idxstats), function(x) { :
  could not find function "mclapply"
Calls: reads2genes_new
Execution halted
Mon Dec  6 15:18:23 CST 2021

I changed the UMIstuffFUN.R file and added ”parallel ::“ at the front
Then there is such an error：

[1] "2021-12-06 15:30:39 CST"
[1] "Coordinate sorting intermediate bam file..."
[bam_sort_core] merging from 0 files and 50 in-memory blocks...
[1] "2021-12-06 15:31:38 CST"
[1] "Hamming distance collapse in barcode chunk 1 out of 1"
Error in rbindlist(rsamtools_reads, fill = TRUE, use.names = TRUE) :
  Item 1 of input is not a data.frame, data.table or list
Calls: reads2genes_new -> rbindlist
In addition: Warning message:
In parallel::mclapply(1:nrow(idxstats), function(x) { :
  all scheduled cores encountered errors in user code

#######################################
Here is my yaml file：
project: B_2_smartseq3
sequence_files:
  file1:
    name: /data/lab/Wangjiachen/20211201-0/d1102s3B/B3_1_S1_L003_R1_001.fastq.gz
    base_definition:
    - cDNA(23-150)
    - UMI(12-19)
    find_pattern: ATTGCGCAATG
  file2:
    name: /data/lab/Wangjiachen/20211201-0/d1102s3B/B3_1_S1_L003_R2_001.fastq.gz
    base_definition: 
    - cDNA(1-150)
  file3:
    name: /data/lab/Wangjiachen/20211201-0/d1102s3B/B3_1_S1_L003_I1_001.fastq.gz
    base_definition: 
    - BC(1-8)
  file4:
    name: /data/lab/Wangjiachen/20211201-0/d1102s3B/B3_1_S1_L003_I2_001.fastq.gz
    base_definition: 
    - BC(1-8)
reference:
  STAR_index: /data/reference/iGenomes/Mus_musculus/Ensembl/GRCm38/Sequence/STARindex_ZUMI/
  GTF_file: /data/reference/iGenomes/Mus_musculus/Ensembl/GRCm38/Annotation/Genes/genes.gtf
  additional_STAR_params: ' --outFilterIntronMotifs RemoveNoncanonicalUnannotated  --clip3pAdapterMMp 0.1 0.1 --clip3pAdapterSeq CTGTCTCTTATACACATCT CTGTCTCTTATACACATCT'
  additional_files: ~
out_dir: /data/tmp/wangjiachen/smartseq3/B3_1/try/
num_threads: 100
mem_limit: 200
filter_cutoffs:
  BC_filter:
    num_bases: 3
    phred: 20
  UMI_filter:
    num_bases: 3
    phred: 20
barcodes:
  barcode_num: null
  barcode_file: /data/tmp/wangjiachen/smartseq3/B3_1/barcode.txt
  barcode_sharing: null
  automatic: no
  BarcodeBinning: 0
  nReadsperCell: 100
  demultiplex: yes
counting_opts:
  introns: yes
  downsampling: 0
  strand: 0
  Ham_Dist: 1
  velocyto: no
  primaryHit: yes
  twoPass: no
make_stats: yes
which_Stage: Filtering
Rscript_exec: Rscript
STAR_exec: STAR
pigz_exec: pigz
samtools_exec: samtools

**Comment by cziegenhain** [comment] 2021-12-06 08:45
Hi, 

If you use the inbuilt conda environment you should get all the packages needed. (just run with zUMIs.sh -c -y myyaml )
Could you post the full verbose from the beginning of the pipeline so I can check what is happening?

Best,
Christoph

**Comment by zmf0621** [comment] 2021-12-06 09:15
Thanks for the help! This is a very useful suggestion. I came to the final result after using the inbuilt environment. Although there was a small problem in the STAR part, everything went well with the bam file I got with before!

**Comment by cziegenhain** [comment] 2021-12-06 20:40
Great! then I will close this issue.

**Comment by Clarkvale** [comment] 2022-03-03 23:56
Hi, I am able reproduce this error. I can't use conda directly because I'm working off the Compute Canada servers and conda isn't allowed. So far I've been attempting to use the docker image via Singularity however this solution is definitely non-trivial.

### Here's the full output log:
`You provided these parameters:
 YAML file:     /home/clarkb/scratch/burst/ss3/scripts/mouse_cross2.yaml
 zUMIs directory:               /project/6002165/clarkb/zUMIs
 STAR executable                STAR
 samtools executable            /home/clarkb/projects/def-robertf/clarkb/samtools/bin/samtools
 pigz executable                pigz
 Rscript executable             Rscript
 RAM limit:   90
 zUMIs version 2.9.7


Thu Feb 24 06:44:30 PST 2022
WARNING: The STAR version used for mapping is 2.7.9a and the STAR index was created using the version 2.7.4a. This may lead to an error while mapping. If you encounter any errors at the mapping stage, please make sure to create the STAR index using STAR 2.7.9a.
Filtering...
Thu Feb 24 09:17:54 PST 2022
[1] "396 barcodes detected."
[1] "17559218 reads were assigned to barcodes that do not correspond to intact cells."
[1] "Found 14769 daughter barcodes that can be binned into 389 parent barcodes."
[1] "Binned barcodes correspond to 17487434 reads."
Mapping...
[1] "2022-02-24 09:34:49 PST"
        STAR --readFilesCommand /home/clarkb/projects/def-robertf/clarkb/samtools/bin/samtools view -@ 2 --outSAMmultNmax 1 --outFilterMultimapNmax 50 --outSAMunmapped Within --outSAMtype BAM Unsorted --quantMode TranscriptomeSAM --genomeDir /home/clarkb/scratch/star_index/n_masked_GRCm38.68_CAST --sjdbGTFfile /home/clarkb/scratch/star_index/mm10/Mus_musculus.GRCm38.68.gtf --runThreadN 6 --sjdbOverhang 149 --readFilesType SAM PE --limitSjdbInsertNsj 2000000 --clip3pAdapterMMp 0.1 0.1 --clip3pAdapterSeq CTGTCTCTTATACACATCT CTGTCTCTTATACACATCT --readFilesIn /home/clarkb/scratch/burst/ss3/zUMI_out/zUMIs_output/.tmpMerge//Smartseq3_Fibroblasts.Smartseq3_Fibroblastsah.filtered.tagged.bam,/home/clarkb/scratch/burst/ss3/zUMI_out/zUMIs_output/.tmpMerge//Smartseq3_Fibroblasts.Smartseq3_Fibroblastsai.filtered.tagged.bam,/home/clarkb/scratch/burst/ss3/zUMI_out/zUMIs_output/.tmpMerge//Smartseq3_Fibroblasts.Smartseq3_Fibroblastsaj.filtered.tagged.bam,/home/clarkb/scratch/burst/ss3/zUMI_out/zUMIs_output/.tmpMerge//Smartseq3_Fibroblasts.Smartseq3_Fibroblastsak.filtered.tagged.bam,/home/clarkb/scratch/burst/ss3/zUMI_out/zUMIs_output/.tmpMerge//Smartseq3_Fibroblasts.Smartseq3_Fibroblastsal.filtered.tagged.bam,/home/clarkb/scratch/burst/ss3/zUMI_out/zUMIs_output/.tmpMerge//Smartseq3_Fibroblasts.Smartseq3_Fibroblastsam.filtered.tagged.bam,/home/clarkb/scratch/burst/ss3/zUMI_out/zUMIs_output/.tmpMerge//Smartseq3_Fibroblasts.Smartseq3_Fibroblastsan.filtered.tagged.bam --outFileNamePrefix /home/clarkb/scratch/burst/ss3/zUMI_out/zUMIs_output/.tmpMap//tmp.Smartseq3_Fibroblasts.2.
        STAR version: 2.7.9a   compiled: 2021-07-08T15:06:22+00:00 build-node.computecanada.ca:/tmp/ebuser/avx2/STAR/2.7.9a/GCCcore-9.3.0/STAR-2.7.9a/source
Feb 24 09:34:51 ..... started STAR run
Feb 24 09:34:52 ..... loading genome
        STAR --readFilesCommand /home/clarkb/projects/def-robertf/clarkb/samtools/bin/samtools view -@ 2 --outSAMmultNmax 1 --outFilterMultimapNmax 50 --outSAMunmapped Within --outSAMtype BAM Unsorted --quantMode TranscriptomeSAM --genomeDir /home/clarkb/scratch/star_index/n_masked_GRCm38.68_CAST --sjdbGTFfile /home/clarkb/scratch/star_index/mm10/Mus_musculus.GRCm38.68.gtf --runThreadN 6 --sjdbOverhang 149 --readFilesType SAM PE --limitSjdbInsertNsj 2000000 --clip3pAdapterMMp 0.1 0.1 --clip3pAdapterSeq CTGTCTCTTATACACATCT CTGTCTCTTATACACATCT --readFilesIn /home/clarkb/scratch/burst/ss3/zUMI_out/zUMIs_output/.tmpMerge//Smartseq3_Fibroblasts.Smartseq3_Fibroblastsaa.filtered.tagged.bam,/home/clarkb/scratch/burst/ss3/zUMI_out/zUMIs_output/.tmpMerge//Smartseq3_Fibroblasts.Smartseq3_Fibroblastsab.filtered.tagged.bam,/home/clarkb/scratch/burst/ss3/zUMI_out/zUMIs_output/.tmpMerge//Smartseq3_Fibroblasts.Smartseq3_Fibroblastsac.filtered.tagged.bam,/home/clarkb/scratch/burst/ss3/zUMI_out/zUMIs_output/.tmpMerge//Smartseq3_Fibroblasts.Smartseq3_Fibroblastsad.filtered.tagged.bam,/home/clarkb/scratch/burst/ss3/zUMI_out/zUMIs_output/.tmpMerge//Smartseq3_Fibroblasts.Smartseq3_Fibroblastsae.filtered.tagged.bam,/home/clarkb/scratch/burst/ss3/zUMI_out/zUMIs_output/.tmpMerge//Smartseq3_Fibroblasts.Smartseq3_Fibroblastsaf.filtered.tagged.bam,/home/clarkb/scratch/burst/ss3/zUMI_out/zUMIs_output/.tmpMerge//Smartseq3_Fibroblasts.Smartseq3_Fibroblastsag.filtered.tagged.bam --outFileNamePrefix /home/clarkb/scratch/burst/ss3/zUMI_out/zUMIs_output/.tmpMap//tmp.Smartseq3_Fibroblasts.1.
        STAR version: 2.7.9a   compiled: 2021-07-08T15:06:22+00:00 build-node.computecanada.ca:/tmp/ebuser/avx2/STAR/2.7.9a/GCCcore-9.3.0/STAR-2.7.9a/source
Feb 24 09:34:51 ..... started STAR run
Feb 24 09:34:53 ..... loading genome
        STAR --readFilesCommand /home/clarkb/projects/def-robertf/clarkb/samtools/bin/samtools view -@ 2 --outSAMmultNmax 1 --outFilterMultimapNmax 50 --outSAMunmapped Within --outSAMtype BAM Unsorted --quantMode TranscriptomeSAM --genomeDir /home/clarkb/scratch/star_index/n_masked_GRCm38.68_CAST --sjdbGTFfile /home/clarkb/scratch/star_index/mm10/Mus_musculus.GRCm38.68.gtf --runThreadN 6 --sjdbOverhang 149 --readFilesType SAM PE --limitSjdbInsertNsj 2000000 --clip3pAdapterMMp 0.1 0.1 --clip3pAdapterSeq CTGTCTCTTATACACATCT CTGTCTCTTATACACATCT --readFilesIn /home/clarkb/scratch/burst/ss3/zUMI_out/zUMIs_output/.tmpMerge//Smartseq3_Fibroblasts.Smartseq3_Fibroblastsao.filtered.tagged.bam,/home/clarkb/scratch/burst/ss3/zUMI_out/zUMIs_output/.tmpMerge//Smartseq3_Fibroblasts.Smartseq3_Fibroblastsap.filtered.tagged.bam,/home/clarkb/scratch/burst/ss3/zUMI_out/zUMIs_output/.tmpMerge//Smartseq3_Fibroblasts.Smartseq3_Fibroblastsaq.filtered.tagged.bam,/home/clarkb/scratch/burst/ss3/zUMI_out/zUMIs_output/.tmpMerge//Smartseq3_Fibroblasts.Smartseq3_Fibroblastsar.filtered.tagged.bam,/home/clarkb/scratch/burst/ss3/zUMI_out/zUMIs_output/.tmpMerge//Smartseq3_Fibroblasts.Smartseq3_Fibroblastsas.filtered.tagged.bam,/home/clarkb/scratch/burst/ss3/zUMI_out/zUMIs_output/.tmpMerge//Smartseq3_Fibroblasts.Smartseq3_Fibroblastsat.filtered.tagged.bam --outFileNamePrefix /home/clarkb/scratch/burst/ss3/zUMI_out/zUMIs_output/.tmpMap//tmp.Smartseq3_Fibroblasts.3.
        STAR version: 2.7.9a   compiled: 2021-07-08T15:06:22+00:00 build-node.computecanada.ca:/tmp/ebuser/avx2/STAR/2.7.9a/GCCcore-9.3.0/STAR-2.7.9a/source
Feb 24 09:34:51 ..... started STAR run
Feb 24 09:34:53 ..... loading genome
Feb 24 09:36:07 ..... processing annotations GTF
Feb 24 09:36:07 ..... processing annotations GTF
Feb 24 09:36:07 ..... processing annotations GTF
Feb 24 09:36:17 ..... inserting junctions into the genome indices
Feb 24 09:36:17 ..... inserting junctions into the genome indices
Feb 24 09:36:17 ..... inserting junctions into the genome indices
Feb 24 09:38:20 ..... started mapping
Feb 24 09:38:22 ..... started mapping
Feb 24 09:38:26 ..... started mapping
Feb 24 12:21:33 ..... finished mapping
Feb 24 12:21:37 ..... finished successfully
Feb 24 12:48:15 ..... finished mapping
Feb 24 12:48:19 ..... finished successfully
Feb 24 12:58:48 ..... finished mapping
Feb 24 12:58:54 ..... finished successfully
Thu Feb 24 13:08:24 PST 2022
Counting...
[1] "2022-02-24 13:08:52 PST"
[1] "1.35e+08 Reads per chunk"
[1] "Loading reference annotation from:"
[1] "/home/clarkb/scratch/burst/ss3/zUMI_out/Smartseq3_Fibroblasts.final_annot.gtf"
[1] "Annotation loaded!"
[1] "Assigning reads to features (ex)"

        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.32.4

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           P Smartseq3_Fibroblasts.filtered.tagged.Alig ... ||
||                                                                            ||
||              Annotation : R data.frame                                     ||
||      Assignment details : <input_file>.featureCounts.bam                   ||
||                      (Note that files are saved to the output directory)   ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 20                                               ||
||                   Level : meta-feature level                               ||
||              Paired-end : yes                                              ||
||      Multimapping reads : counted                                          ||
||     Multiple alignments : primary alignment only                           ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
||          Chimeric reads : not counted                                      ||
||        Both ends mapped : not required                                     ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid9444 ...          ||
||    Features : 244055                                                       ||
||    Meta-features : 37315                                                   ||
||    Chromosomes/contigs : 43                                                ||
||                                                                            ||
|| Process BAM file Smartseq3_Fibroblasts.filtered.tagged.Aligned.out.bam...  ||
||    Paired-end reads are included.                                          ||
||    Assign alignments (paired-end) to features...                           ||
||                                                                            ||
||    WARNING: reads from the same pair were found not adjacent to each       ||
||             other in the input (due to read sorting by location or         ||
||             reporting of multi-mapping read pairs).                        ||
||                                                                            ||
||    Pairing up the read pairs.                                              ||
||                                                                            ||
||    Total alignments : 569248844                                            ||
||    Successfully assigned alignments : 454299881 (79.8%)                    ||
||    Running time : 12.65 minutes                                            ||
||                                                                            ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

[1] "Assigning reads to features (in)"

        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.32.4

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           P Smartseq3_Fibroblasts.filtered.tagged.Alig ... ||
||                                                                            ||
||              Annotation : R data.frame                                     ||
||      Assignment details : <input_file>.featureCounts.bam                   ||
||                      (Note that files are saved to the output directory)   ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 20                                               ||
||                   Level : meta-feature level                               ||
||              Paired-end : yes                                              ||
||      Multimapping reads : counted                                          ||
||     Multiple alignments : primary alignment only                           ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
||          Chimeric reads : not counted                                      ||
||        Both ends mapped : not required                                     ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid9444 ...          ||
||    Features : 196191                                                       ||
||    Meta-features : 21690                                                   ||
||    Chromosomes/contigs : 38                                                ||
||                                                                            ||
|| Process BAM file Smartseq3_Fibroblasts.filtered.tagged.Aligned.out.bam ... ||
||    Paired-end reads are included.                                          ||
||    Assign alignments (paired-end) to features...                           ||
||                                                                            ||
||                                                                            ||
||    WARNING: reads from the same pair were found not adjacent to each       ||
||             other in the input (due to read sorting by location or         ||
||             reporting of multi-mapping read pairs).                        ||
||                                                                            ||
||    Pairing up the read pairs.                                              ||
||                                                                            ||
||    WARNING: reads from the same pair were found not adjacent to each       ||
||             other in the input (due to read sorting by location or         ||
||             reporting of multi-mapping read pairs).                        ||
||                                                                            ||
||    Pairing up the read pairs.                                              ||
||                                                                            ||
||    Total alignments : 569248844                                            ||
||    Successfully assigned alignments : 44806224 (7.9%)                      ||
||    Running time : 12.73 minutes                                            ||
||                                                                            ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

[1] "2022-02-24 13:35:15 PST"
[1] "Coordinate sorting intermediate bam file..."
[bam_sort_core] merging from 120 files and 20 in-memory blocks...
[1] "2022-02-24 15:44:59 PST"
[1] "Hamming distance collapse in barcode chunk 1 out of 5"
Error in rbindlist(rsamtools_reads, fill = TRUE, use.names = TRUE) :
  Item 1 of input is not a data.frame, data.table or list
Calls: reads2genes_new -> rbindlist
In addition: Warning message:
In parallel::mclapply(1:nrow(idxstats), function(x) { :
  all scheduled cores encountered errors in user code
Execution halted
Thu Feb 24 15:45:01 PST 2022
Loading required package: yaml
Loading required package: Matrix
[1] "loomR found"
Error in gzfile(file, "rb") : cannot open the connection
Calls: rds_to_loom -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/home/clarkb/scratch/burst/ss3/zUMI_out/zUMIs_output/expression/Smartseq3_Fibroblasts.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Thu Feb 24 15:45:09 PST 2022
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2022-02-24 15:45:10 PST"
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/home/clarkb/scratch/burst/ss3/zUMI_out/zUMIs_output/expression/Smartseq3_Fibroblasts.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Thu Feb 24 15:45:36 PST 2022`


### And here is the yaml file:

project: Smartseq3_Fibroblasts
sequence_files:
  file1:
    name: /home/clarkb/scratch/burst/ss3/reads/Smartseq3.Fibroblasts.NovaSeq.R1.fastq.gz
    base_definition:
      - cDNA(23-150)
      - UMI(12-19)
    find_pattern: ATTGCGCAATG
  file2:
    name: /home/clarkb/scratch/burst/ss3/reads/Smartseq3.Fibroblasts.NovaSeq.R2.fastq.gz
    base_definition:
      - cDNA(1-150)
  file3:
    name: /home/clarkb/scratch/burst/ss3/reads/Smartseq3.Fibroblasts.NovaSeq.I1.fastq.gz
    base_definition:
      - BC(1-8)
  file4:
    name: /home/clarkb/scratch/burst/ss3/reads/Smartseq3.Fibroblasts.NovaSeq.I2.fastq.gz
    base_definition:
      - BC(1-8)
reference:
  STAR_index: /home/clarkb/scratch/star_index/n_masked_GRCm38.68_CAST
  GTF_file: /home/clarkb/scratch/star_index/mm10/Mus_musculus.GRCm38.68.gtf
  additional_STAR_params: '--limitSjdbInsertNsj 2000000 --clip3pAdapterMMp 0.1 0.1  --clip3pAdapterSeq CTGTCTCTTATACACATCT CTGTCTCTTATACACATCT'
  additional_files:
out_dir: /home/clarkb/scratch/burst/ss3/zUMI_out
num_threads: 20
mem_limit: 90
filter_cutoffs:
  BC_filter:
    num_bases: 3
    phred: 20
  UMI_filter:
    num_bases: 3
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file:
  automatic: yes
  BarcodeBinning: 1
  nReadsperCell: 100
  demultiplex: yes
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 1
  write_ham: yes
  velocyto: no
  primaryHit: yes
  twoPass: no
make_stats: yes
which_Stage: Filtering
samtools_exec: /home/clarkb/projects/def-robertf/clarkb/samtools/bin/samtools
STAR_exec: STAR



Any help would be super appreciated.

**Comment by ROund-code** [comment] 2022-05-06 05:56
Hi, 
Have you fixed that problem? when I run example data, I also produced that error message.
**Here's the full output log:**
 Good news! A newer version of zUMIs is available at https://github.com/sdparekh/zUMIs

-------------


 You provided these parameters:
 YAML file:     runExample.yaml
 zUMIs directory:               /media/nbfs/gongyy/3_smart_seq_rabbit/3_zUMIs
 STAR executable                /home/novelbio/miniconda2/bin/STAR
 samtools executable            /usr/bin/samtools
 pigz executable                /usr/bin/pigz
 Rscript executable             /usr/bin/Rscript
 RAM limit:   40
 zUMIs version 2.9.7


Thu May  5 15:42:15 CST 2022
Filtering...
Thu May  5 15:42:32 CST 2022
[1] "43 barcodes detected."
[1] "193783 reads were assigned to barcodes that do not correspond to intact cells."
Mapping...
[1] "2022-05-05 15:42:37 CST"
Warning message:
NAs introduced by coercion
May 05 15:42:38 ..... started STAR run
May 05 15:42:38 ..... loading genome
May 05 15:42:39 ..... processing annotations GTF
May 05 15:42:39 ..... inserting junctions into the genome indices
May 05 15:42:45 ..... started mapping
May 05 15:45:22 ..... finished mapping
May 05 15:45:23 ..... finished successfully
Thu May  5 15:45:23 CST 2022
Counting...
[1] "2022-05-05 15:45:42 CST"
[1] "1.8e+08 Reads per chunk"
[1] "Loading reference annotation from:"
[1] "/media/nbfs/gongyy/3_smart_seq_rabbit/0_example/output/Example.final_annot.gtf"
[1] "Annotation loaded!"
[1] "Assigning reads to features (ex)"

        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.32.4

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S Example.filtered.tagged.Aligned.out.bam        ||
||                                                                            ||
||              Annotation : R data.frame                                     ||
||      Assignment details : <input_file>.featureCounts.bam                   ||
||                      (Note that files are saved to the output directory)   ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 8                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : yes                                              ||
||      Multimapping reads : counted                                          ||
||     Multiple alignments : primary alignment only                           ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
||          Chimeric reads : not counted                                      ||
||        Both ends mapped : not required                                     ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid10627 ...         ||
||    Features : 7370                                                         ||
||    Meta-features : 1353                                                    ||
||    Chromosomes/contigs : 1                                                 ||
||                                                                            ||
|| Process BAM file Example.filtered.tagged.Aligned.out.bam...                ||
||    Single-end reads are included.                                          ||
||    Assign alignments to features...                                        ||
||    Total alignments : 853296                                               ||
||    Successfully assigned alignments : 20901 (2.4%)                         ||
||    Running time : 0.03 minutes                                             ||
||                                                                            ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

[1] "Assigning reads to features (in)"

        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.32.4

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S Example.filtered.tagged.Aligned.out.bam.ex ... ||
||                                                                            ||
||              Annotation : R data.frame                                     ||
||      Assignment details : <input_file>.featureCounts.bam                   ||
||                      (Note that files are saved to the output directory)   ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 8                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : yes                                              ||
||      Multimapping reads : counted                                          ||
||     Multiple alignments : primary alignment only                           ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
||          Chimeric reads : not counted                                      ||
||        Both ends mapped : not required                                     ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid10627 ...         ||
||    Features : 4843                                                         ||
||    Meta-features : 677                                                     ||
||    Chromosomes/contigs : 1                                                 ||
||                                                                            ||
|| Process BAM file Example.filtered.tagged.Aligned.out.bam.ex.featureCou ... ||
||    Single-end reads are included.                                          ||
||    Assign alignments to features...                                        ||
||    Total alignments : 853296                                               ||
||    Successfully assigned alignments : 43386 (5.1%)                         ||
||    Running time : 0.03 minutes                                             ||
||                                                                            ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

[1] "2022-05-05 15:46:03 CST"
[1] "Coordinate sorting final bam file..."
[bam_sort_core] merging from 0 files and 8 in-memory blocks...
[1] "2022-05-05 15:46:06 CST"
[1] "Here are the detected subsampling options:"
[1] "Automatic downsampling"
[1] "Working on barcode chunk 1 out of 1"
[1] "Processing 43 barcodes in this chunk..."
Error in mclapply(1:nrow(idxstats), function(x) { :
  could not find function "mclapply"
Calls: reads2genes_new
Execution halted
Thu May  5 15:46:07 CST 2022
Loading required package: yaml
Loading required package: Matrix
[1] "loomR found"
Error in gzfile(file, "rb") : cannot open the connection
Calls: rds_to_loom -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/media/nbfs/gongyy/3_smart_seq_rabbit/0_example/output/zUMIs_output/expression/Example.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Thu May  5 15:46:12 CST 2022
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2022-05-05 15:46:12 CST"
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/media/nbfs/gongyy/3_smart_seq_rabbit/0_example/output/zUMIs_output/expression/Example.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Thu May  5 15:46:25 CST 2022

**Comment by cziegenhain** [comment] 2022-05-06 08:35
Hi,

I have found that this is caused by a change in RSamtools which is one of the dependencies used. 
Hopefully I find the time to push the fix later today - in the meantime the inbuilt conda environment remains as an option with the functional combination of versions of all dependencies.

Best,
Christoph

**Comment by ROund-code** [comment] 2022-05-06 09:25
Hi,

Thanks for your help and prompt reply, I will try to use the inbuilt conda environment as you suggested, will let you know the results. also it will be great if you could fix that RSamtools problems!

Best Regards,
Yvonne

**Comment by Clarkvale** [comment] 2022-05-06 16:26
I resolved the problem by using TomKellyGenetics' branch with some of my own minor fixes. The problem seem to be parsing '*' symbols in bamfiles. I also had to the parallel package to the namespace in the functions R script. My fork is here: https://github.com/Clarkvale/zUMIs

**Comment by cziegenhain** [comment] 2022-05-06 18:37
I pushed the fix for the change in Rsamtools behavior earlier today.

**Closed by cziegenhain** 2022-05-06 18:37 UTC

**Comment by ROund-code** [comment] 2022-05-09 10:01
Hi cziegenhain and clarkvale:

The updated version works well for me, thank you for your generous help.

Best Regards,
Yvonne
